version: "3.4"

services:
  db:
    image: postgres:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./data/db:/var/lib/postgresql/data
#    - ./logs/pg/:/var/log/pg
    ports:
    - 5433:5432
    networks:
      - internal

  webserver:
    build: config/nginx
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    working_dir: /application
    volumes:
    - ./app:/application
    - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./logs/nginx:/var/log/nginx
    depends_on:
      - db
      - php-fpm
    ports:
    - "${NGINX_EXTERNAL_PORT}:80"
    networks:
    - internal

  php-fpm:
    build: config/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    working_dir: /application

    volumes:
    - ./app:/application:cached
    - /application/vendor
    - /application/var
    - /application/node_modules
    - ./config/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./config/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=${COMPOSE_PROJECT_NAME}-docker"
    depends_on:
      - redis
    networks:
      - internal

  redis:
    image: "redis:alpine"
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.220.0/28
