version: "3.4"
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}.0/24

services:
  db:
    image: postgres:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./data/db:/var/lib/postgresql/data
#    - ./logs/pg/:/var/log/pg
    ports:
    - 5433:5432
    networks:
      internal:
        ipv4_address: ${SUBNET_IP}.6

  webserver:
    build: config/nginx
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    working_dir: /application
    volumes:
    - ./app:/application
    - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./logs/nginx:/var/log/nginx
    depends_on:
      - db
      - php-fpm
    ports:
    - "${NGINX_EXTERNAL_PORT}:80"
    networks:
      internal:
        ipv4_address: ${SUBNET_IP}.3

  php-fpm:
    build: config/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    working_dir: /application

    volumes:
    - ./app:/application:cached
#    - ./config/php-fpm/php-fpm.ini:/etc/php8/conf.d/99-overrides.ini
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - redis
    networks:
      internal:
        ipv4_address: ${SUBNET_IP}.4

  redis:
    image: "redis:alpine"
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    networks:
      internal:
        ipv4_address: ${SUBNET_IP}.5
